server:
  port: 9092

spring:
  security:
    user:
      name: workforce
      password: solutions
  datasource:
    url: jdbc:postgresql://localhost:5432/HRPCommentDB
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true