package com.umit.utility.enums;

public enum EEquipmentType {

    COMPUTER, PHONE, TABLET, HEADPHONES,
    DESK, CHAIR, KEYBOARD, MOUSE, MONITOR, PRINTER, SCANNER, PROJECTOR, FILE_CABINET,
    STATIONERY, LAPTOP_BAG, EXTERNAL_HARD_DRIVE, USB_FLASH_DRIVE, ETHERNET_CABLE,
    POWER_STRIP, SURGE_PROTECTOR;

}
