package com.umit.utility.enums;

public enum EExpenseType {

    OFFICE_RENT,
    UTILITIES,
    OFFICE_SUPPLIES,
    EQUIPMENT_MAINTENANCE,
    ADVERTISING,
    MARKETING,
    TRAVEL,
    TRAINING,
    CONSULTING_FEES,
    SOFTWARE_SUBSCRIPTIONS,
    HARDWARE_PURCHASE,
    INSURANCE,
    LEGAL_FEES,
    ACCOUNTING_FEES,
    EMPLOYEE_SALARIES,
    CONTRACTOR_FEES,
    TAXES,
    PRINTING,
    OTHER

}
