package com.umit.utility.enums;

public enum ELeaveType {

    ANNUAL_LEAVE,
    SICK_LEAVE,
    UNPAID_LEAVE,
    MATERNITY_LEAVE,
    PATERNITY_LEAVE,
    FAMILY_LEAVE,
    BEREAVEMENT_LEAVE,
    STUDY_LEAVE,
    HALF_DAY_LEAVE,
    SPECIAL_LEAVE,
    COMPASSIONATE_LEAVE,
    EMERGENCY_LEAVE,
    VOLUNTEERING_LEAVE,
    PUBLIC_HOLIDAY,
    WORK_FROM_HOME,
    FURLOUGH

}
