server:
  port: 80


spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      default-filters:
        # gelen URL -> http://localhost/auth/get-service-name
        # düzenlenecek ->  segment -> get-service-name
        # düzenlenen -> http://localhost:9090/dev/v1/auth/get-service-name
        - RewritePath= /(?<segment>.*) , /dev/v1/$\{segment}
      routes:
        - id: auth-service
          # Olması gereken          -> http://localhost:9090/dev/v1/auth/get-service-name
          uri: http://localhost:9091 # http://localhost:9090/auth/get-service-name
          predicates:
            - Path=/auth/**  # http://localhost/auth/get-service-name
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true #!
                name: auth
                fallbackUri: forward:/fallback/auth
        - id: manager-service
          uri: http://localhost:9095
          predicates:
            - Path=/manager/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                name: manager
                fallbackUri: forward:/fallback/manager